import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { 
  TrendingUp, 
  TrendingDown, 
  Target, 
  AlertTriangle,
  Clock,
  Activity,
  CheckCircle2,
  XCircle,
  BarChart3
} from 'lucide-react'
import api from '../lib/api'

interface Setup {
  id: string
  symbol: string
  direction: string
  status: string
  active: boolean
  entryZone: { low: number; high: number }
  stopLoss: number
  targets: number[]
  confidence: number
  riskLevel: string
  strategyType: string
  timeframe: string
  reasoning: string
  createdAt: string
  expiresAt: string | null
}

export default function SetupHistory() {
  const [setups, setSetups] = useState<Setup[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState<'all' | 'active' | 'expired' | 'triggered'>('all')
  const [tier, setTier] = useState('basic')
  const [_canAccessFullHistory, setCanAccessFullHistory] = useState(false)

  useEffect(() => {
    loadHistory()
  }, [])

  const loadHistory = async () => {
    try {
      const { data } = await api.get('/setups/history')
      setSetups(data.setups || [])
      setTier(data.tier || 'basic')
      setCanAccessFullHistory(data.canAccessFullHistory)
    } catch (error) {
      console.error('Failed to load setup history:', error)
    } finally {
      setLoading(false)
    }
  }

  const filteredSetups = setups.filter(s => {
    if (filter === 'all') return true
    if (filter === 'active') return s.active && s.status !== 'expired'
    if (filter === 'expired') return !s.active || s.status === 'expired'
    if (filter === 'triggered') return s.status === 'triggered' || s.status === 'near_trigger'
    return true
  })

  const formatDate = (dateStr: string) => {
    return new Date(dateStr).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    })
  }

  const getStatusIcon = (status: string, active: boolean) => {
    if (!active) return <XCircle className="w-4 h-4 text-gray-400" />
    switch (status) {
      case 'triggered': return <CheckCircle2 className="w-4 h-4 text-neon-green" />
      case 'near_trigger': return <Target className="w-4 h-4 text-neon-yellow" />
      case 'forming': return <Activity className="w-4 h-4 text-neon-cyan" />
      default: return <Clock className="w-4 h-4 text-gray-400" />
    }
  }

  const getStatusColor = (status: string, active: boolean) => {
    if (!active) return 'bg-gray-500/20 text-gray-400 border-gray-500/40'
    switch (status) {
      case 'triggered': return 'bg-neon-green/20 text-neon-green border-neon-green/40'
      case 'near_trigger': return 'bg-neon-yellow/20 text-neon-yellow border-neon-yellow/40'
      case 'forming': return 'bg-neon-cyan/20 text-neon-cyan border-neon-cyan/40'
      default: return 'bg-gray-500/20 text-gray-400 border-gray-500/40'
    }
  }

  const getStatusText = (status: string, active: boolean) => {
    if (!active) return 'EXPIRED'
    return status.toUpperCase()
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-black text-white">Setup History</h1>
          <p className="text-gray-400 mt-1">Complete archive of all trade setups generated by Neon Alpha</p>
        </div>
        <div className="flex items-center gap-2 text-sm text-gray-400">
          <BarChart3 className="w-4 h-4" />
          <span>{setups.length} total setups</span>
        </div>
      </div>

        {/* Stats Summary */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="glass rounded-xl p-4"
          >
            <div className="text-xs text-gray-400 mb-1">Active Setups</div>
            <div className="text-2xl font-bold text-neon-cyan">
              {setups.filter(s => s.active).length}
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="glass rounded-xl p-4"
          >
            <div className="text-xs text-gray-400 mb-1">Triggered</div>
            <div className="text-2xl font-bold text-neon-green">
              {setups.filter(s => s.status === 'triggered').length}
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="glass rounded-xl p-4"
          >
            <div className="text-xs text-gray-400 mb-1">Expired</div>
            <div className="text-2xl font-bold text-gray-400">
              {setups.filter(s => !s.active || s.status === 'expired').length}
            </div>
          </motion.div>

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="glass rounded-xl p-4"
          >
            <div className="text-xs text-gray-400 mb-1">Win Rate</div>
            <div className="text-2xl font-bold text-white">
              {setups.filter(s => s.status === 'triggered').length > 0
                ? Math.round((setups.filter(s => s.status === 'triggered').length / setups.filter(s => s.status === 'triggered' || s.status === 'expired').length) * 100)
                : 0}%
            </div>
          </motion.div>
        </div>

        {/* Filters */}
        <div className="flex gap-2">
          {(['all', 'active', 'triggered', 'expired'] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                filter === f 
                  ? 'bg-neon-cyan/20 text-neon-cyan border border-neon-cyan/40' 
                  : 'text-gray-400 hover:text-white hover:bg-dark-700'
              }`}
            >
              {f.charAt(0).toUpperCase() + f.slice(1)}
            </button>
          ))}
        </div>

        {/* Tier Notice */}
        {tier === 'basic' && (
          <div className="glass rounded-lg p-4 border-yellow-500/30 bg-yellow-500/10">
            <div className="flex items-center gap-2 text-yellow-400 text-sm">
              <AlertTriangle className="w-4 h-4" />
              <span>Starter plan: Limited to 20 setups. Upgrade to PRO for full history.</span>
            </div>
          </div>
        )}

        {/* Setups Table */}
        {loading ? (
          <div className="flex justify-center py-12">
            <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-neon-cyan"></div>
          </div>
        ) : (
          <div className="glass rounded-xl overflow-hidden">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-700/50">
                  <th className="text-left py-3 px-4 text-xs font-medium text-gray-400">Setup</th>
                  <th className="text-left py-3 px-4 text-xs font-medium text-gray-400">Entry Zone</th>
                  <th className="text-left py-3 px-4 text-xs font-medium text-gray-400">Targets</th>
                  <th className="text-left py-3 px-4 text-xs font-medium text-gray-400">Risk</th>
                  <th className="text-left py-3 px-4 text-xs font-medium text-gray-400">Status</th>
                  <th className="text-left py-3 px-4 text-xs font-medium text-gray-400">Created</th>
                </tr>
              </thead>
              <tbody>
                {filteredSetups.map((setup, index) => (
                  <motion.tr
                    key={setup.id}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="border-b border-gray-700/30 hover:bg-dark-700/30"
                  >
                    <td className="py-3 px-4">
                      <div className="flex items-center gap-3">
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${
                          setup.direction === 'bullish' ? 'bg-neon-green/20' : 'bg-red-500/20'
                        }`}>
                          {setup.direction === 'bullish' ? (
                            <TrendingUp className="w-4 h-4 text-neon-green" />
                          ) : (
                            <TrendingDown className="w-4 h-4 text-red-400" />
                          )}
                        </div>
                        <div>
                          <div className="font-semibold text-white">{setup.symbol}</div>
                          <div className="text-xs text-gray-500">{setup.timeframe} • {setup.strategyType}</div>
                        </div>
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <div className="text-sm text-white">
                        {setup.entryZone.low.toFixed(4)} - {setup.entryZone.high.toFixed(4)}
                      </div>
                      <div className="text-xs text-gray-500">
                        SL: {setup.stopLoss?.toFixed(4) || 'N/A'}
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <div className="flex gap-1">
                        {setup.targets.slice(0, 3).map((target, i) => (
                          <span key={i} className="text-xs bg-neon-cyan/20 text-neon-cyan px-2 py-0.5 rounded">
                            {target.toFixed(3)}
                          </span>
                        ))}
                      </div>
                    </td>
                    <td className="py-3 px-4">
                      <span className={`text-xs px-2 py-1 rounded-full ${
                        setup.riskLevel === 'LOW' ? 'bg-neon-green/20 text-neon-green' :
                        setup.riskLevel === 'MEDIUM' ? 'bg-neon-yellow/20 text-neon-yellow' :
                        'bg-red-500/20 text-red-400'
                      }`}>
                        {setup.riskLevel}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      <span className={`inline-flex items-center gap-1.5 px-2 py-1 rounded-full text-xs font-medium border ${getStatusColor(setup.status, setup.active)}`}>
                        {getStatusIcon(setup.status, setup.active)}
                        {getStatusText(setup.status, setup.active)}
                      </span>
                    </td>
                    <td className="py-3 px-4 text-sm text-gray-400">
                      {formatDate(setup.createdAt)}
                    </td>
                  </motion.tr>
                ))}
              </tbody>
            </table>
            {filteredSetups.length === 0 && (
              <div className="text-center py-12 text-gray-500">
                No setups found for this filter.
              </div>
            )}
          </div>
        )}
      </div>
  )
}
